import type { Task, Story, Pattern, ActivityItem } from './types';

// Mock Tasks
export const mockTasks: Task[] = [
  {
    id: 'task-001',
    name: 'User Authentication',
    description: 'Implement email/password login and OAuth (Google, GitHub) support',
    branchName: 'ralph/user-auth',
    status: 'running',
    priority: 1,
    currentIteration: 2,
    maxIterations: 10,
    worktreePath: '.worktrees/task-001/',
    metadataPath: '.ralph/tasks/task-001/',
    createdAt: new Date('2026-01-20T10:00:00'),
    updatedAt: new Date('2026-01-21T15:30:00'),
    startedAt: new Date('2026-01-20T11:00:00'),
  },
  {
    id: 'task-002',
    name: 'Dark Mode',
    description: 'Add dark mode toggle with theme persistence',
    branchName: 'ralph/dark-mode',
    status: 'review',
    priority: 2,
    currentIteration: 5,
    maxIterations: 10,
    worktreePath: '.worktrees/task-002/',
    metadataPath: '.ralph/tasks/task-002/',
    createdAt: new Date('2026-01-19T14:00:00'),
    updatedAt: new Date('2026-01-21T14:45:00'),
    startedAt: new Date('2026-01-19T15:00:00'),
    completedAt: new Date('2026-01-21T14:45:00'),
  },
  {
    id: 'task-003',
    name: 'API Refactoring',
    description: 'Refactor REST API to GraphQL',
    branchName: 'ralph/api-refactor',
    status: 'queued',
    priority: 3,
    currentIteration: 0,
    maxIterations: 10,
    worktreePath: '.worktrees/task-003/',
    metadataPath: '.ralph/tasks/task-003/',
    createdAt: new Date('2026-01-21T09:00:00'),
    updatedAt: new Date('2026-01-21T09:00:00'),
  },
  {
    id: 'task-004',
    name: 'Database Schema',
    description: 'Design and implement new database schema',
    branchName: 'ralph/db-schema',
    status: 'merged',
    priority: 1,
    currentIteration: 3,
    maxIterations: 10,
    worktreePath: '.worktrees/task-004/',
    metadataPath: '.ralph/tasks/task-004/',
    createdAt: new Date('2026-01-18T10:00:00'),
    updatedAt: new Date('2026-01-19T16:00:00'),
    startedAt: new Date('2026-01-18T11:00:00'),
    completedAt: new Date('2026-01-19T16:00:00'),
  },
];

// Mock Stories for task-001
export const mockStories: Story[] = [
  {
    id: 'US-001',
    taskId: 'task-001',
    title: 'Email Login',
    description: 'Implement email/password authentication',
    acceptanceCriteria: [
      'User can register with email and password',
      'User can login with email and password',
      'Password must be hashed and salted',
    ],
    priority: 1,
    passes: true,
    threadUrl: 'https://ampcode.com/threads/abc123',
    iterationCompleted: 1,
    completedAt: new Date('2026-01-20T14:00:00'),
  },
  {
    id: 'US-002',
    taskId: 'task-001',
    title: 'Registration Form',
    description: 'Create user registration form component',
    acceptanceCriteria: [
      'Form includes email, password, confirm password fields',
      'Client-side validation for email format and password strength',
      'Display error messages for validation failures',
    ],
    priority: 2,
    passes: true,
    iterationCompleted: 1,
    completedAt: new Date('2026-01-20T16:00:00'),
  },
  {
    id: 'US-003',
    taskId: 'task-001',
    title: 'JWT Token Management',
    description: 'Implement JWT token generation and validation',
    acceptanceCriteria: [
      'Generate JWT tokens on successful login',
      'Validate JWT tokens on protected routes',
      'Implement refresh token rotation',
    ],
    priority: 3,
    passes: true,
    iterationCompleted: 2,
    completedAt: new Date('2026-01-21T10:00:00'),
  },
  {
    id: 'US-004',
    taskId: 'task-001',
    title: 'Google OAuth',
    description: 'Integrate Google OAuth authentication',
    acceptanceCriteria: [
      'User can login with Google account',
      'Google profile data is stored in database',
      'OAuth flow handles errors gracefully',
    ],
    priority: 4,
    passes: false,
    startedAt: new Date('2026-01-21T14:00:00'),
  },
  {
    id: 'US-005',
    taskId: 'task-001',
    title: 'GitHub OAuth',
    description: 'Integrate GitHub OAuth authentication',
    acceptanceCriteria: [
      'User can login with GitHub account',
      'GitHub profile data is stored in database',
    ],
    priority: 5,
    passes: false,
  },
];

// Mock Patterns
export const mockPatterns: Pattern[] = [
  {
    id: 1,
    pattern: 'Use NextAuth [...nextauth].ts pattern for authentication setup',
    category: 'convention',
    sourceFile: 'src/app/api/auth/[...nextauth]/route.ts',
    createdAt: new Date('2026-01-20T12:00:00'),
    promotedAt: new Date('2026-01-20T18:00:00'),
  },
  {
    id: 2,
    pattern: 'Always use IF NOT EXISTS for database migrations',
    category: 'gotcha',
    sourceFile: 'prisma/migrations/001_init.sql',
    createdAt: new Date('2026-01-18T14:00:00'),
    promotedAt: new Date('2026-01-19T10:00:00'),
  },
  {
    id: 3,
    pattern: 'Wrap page components with ErrorBoundary',
    category: 'convention',
    sourceFile: 'src/app/layout.tsx',
    createdAt: new Date('2026-01-19T09:00:00'),
  },
  {
    id: 4,
    pattern: 'Use sql template for raw queries with aggregations',
    category: 'tip',
    createdAt: new Date('2026-01-20T16:00:00'),
  },
];

// Mock Activity Feed
export const mockActivity: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'task_merged',
    taskId: 'task-004',
    taskName: 'Database Schema',
    message: 'merged to main',
    timestamp: new Date('2026-01-19T16:00:00'),
  },
  {
    id: 'act-002',
    type: 'iteration_completed',
    taskId: 'task-001',
    taskName: 'User Authentication',
    message: 'iteration #2 completed',
    timestamp: new Date('2026-01-21T15:00:00'),
  },
  {
    id: 'act-003',
    type: 'task_started',
    taskId: 'task-002',
    taskName: 'Dark Mode',
    message: 'started',
    timestamp: new Date('2026-01-19T15:00:00'),
  },
  {
    id: 'act-004',
    type: 'task_created',
    taskId: 'task-003',
    taskName: 'API Refactor',
    message: 'PRD approved',
    timestamp: new Date('2026-01-21T09:00:00'),
  },
];
